spring:
  application:
    name: hotspot
  datasource:
    url: jdbc:postgresql://localhost:5432/hotspotdb
    username: hotspotuser
    password: hotspot
    driver-class-name: org.postgresql.Driver

  jpa:

    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

app:
  invites:
    initial-count: 5
